---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---


```{r message=FALSE}
options(warn=-1)
options(digits=3)

# load packages
library(dplyr)
library(ggplot2)
library(tidyr)
library(reshape2)
```


```{r}
#
# load data - subject responses
#
response = read.csv(file = "./data/subject responses - accuracy analysis.csv", header=TRUE, sep=",")

response$pre_post = factor(response$pre_post, levels=c('pretest','posttest'), labels = c("pretest", "posttest"))
```

## Accuracy analysis when ML offered correct vs incorrect advice

```{r message=FALSE}
#
# calculate the difference of pre- and post-test accuracy  
# note: ML incorrect prediction occurred in high complex (Hard) surgical cases. 
#
pre_post_accuracy = response %>% 
  filter(qz_level == "HARD") %>%
  group_by(study_group, pre_post, ml_correct, user_id) %>%
  summarize(mean.score = mean(correct), 
            sd.score =sd(correct),
            n.score = n()) 

pre_post_accuracy_pvt = pre_post_accuracy %>%
  select(-c(sd.score, n.score)) %>%
  pivot_wider(names_from=pre_post, values_from=mean.score) %>%
  mutate(diff = posttest - pretest)

```

```{r}
#
#  functions for the lower and upper bounds of confidence interval 
#
lower_ci <- function(mean, se, n, conf_level = 0.95){
  lower_ci <- mean - qt(1 - ((1 - conf_level) / 2), n - 1) * se
}
upper_ci <- function(mean, se, n, conf_level = 0.95){
  upper_ci <- mean + qt(1 - ((1 - conf_level) / 2), n - 1) * se
}
```


```{r}
pre_post_accuracy_unpviot = pre_post_accuracy_pvt %>% 
  melt(, id.vars=c("study_group", "ml_correct", "user_id"), 
       measure.vars = c("pretest", "posttest", "diff"))

```


```{r message=FALSE}

pre_post_result = pre_post_accuracy_unpviot %>% 
  group_by(study_group, ml_correct, variable) %>%
  summarize(smean = round(mean(value),3), 
            ssd = round(sd(value),3),
            n = n()) %>%
  mutate(se = ssd / sqrt(n),
         lower_ci = round(lower_ci(smean, se, n),3),
         upper_ci = round(upper_ci(smean, se, n),3))

pre_post_result
```


```{r}
#
# The paired t-test to measure the significance of the secondary outcomes of ML correct vs incorrect 
# (p-values in Table 3)
#
for (type in unique(pre_post_accuracy_pvt$study_group)) {
  for (correct in unique(pre_post_accuracy_pvt$ml_correct)) {
    sub_data = pre_post_accuracy_pvt %>% filter(study_group == type, ml_correct == correct)
    mean_post = sub_data$posttest
    mean_pre = sub_data$pretest
    cat(type, correct)
    result = t.test(mean_post, mean_pre, paired = TRUE, alternative = "two.sided", exact = FALSE)
    print(result)
    print(result[3])
  }
}
  

```



# Visualization

```{r message=FALSE}
accuracy_ml = response %>% 
  group_by(study_group, pre_post, user_id, ml_correct, qz_level) %>%
  summarize(cnt= n(), 
            score = mean(correct)) %>%
  group_by(study_group, ml_correct, qz_level, pre_post) %>%
  summarize(mean.score = mean(score)) %>%
  mutate(qz_level = factor(qz_level, levels=c("EASY","HARD"), labels = c("Easy", "Hard"))) 

```


```{r}

# The errorbars overlapped, so use position_dodge to move them horizontally
pd <- position_dodge(0.1) 

alp2 = accuracy_ml %>% 
  ggplot(aes(x = pre_post, y=mean.score, group = study_group, color=factor(study_group))) +
  # geom_errorbar(aes(ymin=mean.score-se.score, ymax=mean.score+se.score), colour="black", width=.1, position=pd) +
  geom_line(size=1) +
  geom_point() +
  # xlab("Pre- and Post Intervention") + 
  theme(axis.title.x=element_blank()) +
  theme(text = element_text(size=15)) +
  ylab("Accuracy") +
  scale_color_manual(name="Intervention", 
                     labels=c(expression(EB), expression(ML[DR]), expression(ML[IR])), 
                     values=c("#999999", "#E69F00", "#56B4E9")) +
  theme(legend.text.align = 0) +
  facet_wrap(~ml_correct+qz_level)

alp2

```

```{r}
ggsave(filename = "accuracy_by_ML_rec_correct.png", width=8, height=4, device='png', dpi=200)
```


